### ISSUE TITLE
Explain what are the differences and advantages compared to RxDB

### ISSUE THREAD

**Issue by etienned** [clientdb/clientdb#12]
Sorry, it's not a real issue, but it's the only way I found to ask. So, what are the main differences between [RxDB](https://rxdb.info/) and ClientDB? What are the main advantages of clientDB over RxDB?

Thanks

**Comment by pie6k** [comment]
In many ways it is similar. A few differences I did notice:

- all operations in clientdb are sync (in-memory) vs async/await for RxDB
- clientdb includes sync server (work in progress #10 ) that handles syncing any server with any client (and is not constrained to couchdb, etc)
- there are no constrains on soft-deletes
- clientdb server can track lost permissions syncing (eg. you set is_disabled on some of team memberships and given member will receive sync request to remove all team assets)
- there are bunch of API choices, but this is matter of preference

**Comment by etienned** [comment]
Thanks Adam for this info! I'll keep following your project.

Maybe you should put this info somewhere in your docs.
